language: ruby
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: "bundle exec rake travis --trace"
gemfile:
  - Gemfile.ci
rvm:
  - 1.9.3
branches:
  only:
    - develop
    - master
